/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ConfirmationIdRouteImport } from './routes/confirmation.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as AdminServicesIdRouteImport } from './routes/admin.services.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ConfirmationIdRoute = ConfirmationIdRouteImport.update({
  id: '/confirmation/$id',
  path: '/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services': typeof AdminServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/services': typeof ServicesRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/services'
    | '/admin/services'
    | '/admin/settings'
    | '/confirmation/$id'
    | '/admin/'
    | '/admin/services/$id'
    | '/admin/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/services'
    | '/admin/settings'
    | '/confirmation/$id'
    | '/admin'
    | '/admin/services/$id'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/services'
    | '/admin/services'
    | '/admin/settings'
    | '/confirmation/$id'
    | '/admin/'
    | '/admin/services/$id'
    | '/admin/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ServicesRoute: typeof ServicesRoute
  ConfirmationIdRoute: typeof ConfirmationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/confirmation/$id': {
      id: '/confirmation/$id'
      path: '/confirmation/$id'
      fullPath: '/confirmation/$id'
      preLoaderRoute: typeof ConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminServicesRoute
    }
  }
}

interface AdminServicesRouteChildren {
  AdminServicesIdRoute: typeof AdminServicesIdRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIdRoute: AdminServicesIdRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ServicesRoute: ServicesRoute,
  ConfirmationIdRoute: ConfirmationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
